FROM python:latest

RUN apt-get update
RUN apt-get install -y python3-pip

COPY requirements.txt /app/requirements.txt

RUN pip install -r /app/requirements.txt

COPY . /app

WORKDIR /app
CMD ["python", "app.py"]
